version: '3.8'

# 定义通用的健康检查配置
x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 3

services:
  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - dhcp-network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web应用服务
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@host.docker.internal:${MYSQL_PORT}/${MYSQL_DATABASE}
      - REDIS_URL=redis://host.docker.internal:6379/0
      - KEA_CTRL_AGENT_URL=${KEA_CTRL_AGENT_URL}
      - BIND9_RNDC_KEY=${BIND9_RNDC_KEY}
    networks:
      - dhcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEB_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: on-failure

networks:
  dhcp-network:
    driver: bridge 